### ISSUE TITLE
Make peerDependencies as dependencies

### ISSUE THREAD

**Issue by namenu** [ridi/eslint-config#1]
When using this you have to install 1+5 packages as devDependencies like below.
```
npm install --save-dev eslint-config-ridibooks eslint-config-airbnb eslint eslint-plugin-import eslint-plugin-jsx-ally eslint-plugin-react
```
I think the installation procedure should be more concise.

Though it may not flexible to be up-to-date, how about marking these packages as **dependencies**?
Then you can just run ```npm install eslint-config-ridibooks``` and it'll work like a charm.

**Comment by kyungmi** [comment]
Yes. I was also slightly worried about that.
If we decided to use only a specific version of ESLint configurations of Airbnb, we don't need to remain these dependencies as peer dependencies.

But I think It's good to make an exception on the `eslint` package.

I will add those packages as dependencies.
