### ISSUE TITLE
`plugin:flowtype/recommended` 추가

### ISSUE THREAD

**Issue by kyungmi** [ridi/eslint-config#11]

**Comment by namenu** [comment]
@kyungmi 실수로 닫았다가 다시 열었습니다.  😅

Flow는 ridibooks-electron에서만 사용 중인데요, 혹시 위 플러그인을 추가할 경우 모든 프로젝트에 불필요하게 의존성이 추가되지는 않나요?

**Comment by kyungmi** [comment]
@namenu 엄청 오래된 이슈군요 ㄷㄷ
아무래도 dev env 에서만 추가되는 의존성이라서 크게 문제될 것 같진 않지만, 일렉트론 뷰어에서도 Flow 사용을 확대할 계획이 없고, 타입스크립트 도입을 다시 진지하게 생각중이어서 이 이슈는 닫아도 무방할 것 같아요. ㅎㅎ
