### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by namenu** [ridi/eslint-config#4]
This is a rule set for company-wide guidance.

Current repo/package name is alienating Ridistory.

Better name I suggest is `@ridi/eslint-config`.

Any idea?

---

- [x] Transfer project to ridi
- [x] Fix package.json and publish to npm
- [x] npm deprecated
- [x] Travis-CI
- [x] VersionEye
- [x] Greenkeeper

**Comment by kyungmi** [comment]
@namenu 
`@ridi/eslint-config` is good to me too.
How about `eslint-config-ridi`? I think it is another proper name like `eslint-config-airbnb` or [`eslint-config-google`](https://www.npmjs.com/package/eslint-config-google).

**Comment by namenu** [comment]
The examples you mentioned had been published before the scope feature appeared.
In my opinion, we're in the middle of transition so `@ridi/eslint-config` is more promising.

**Comment by kyungmi** [comment]
Yep. I'll add the package to npm with the name. 
The current package will be deprecated. I'll keep it for a period of time.

Oh! Are you going to do it yourself? 👍

**Comment by kyungmi** [comment]
Complete all!
